services:
  swaggerui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swaggerui
    environment:
      - EMBEDDING=true
      - SWAGGER_JSON_URL=https://raw.githubusercontent.com/atrakic/callback-api/refs/heads/main/openapi.json
    ports:
      - 8080:8080
