services:
  api:
    build: ./src/api
    container_name: api
    ports:
      - 8000:8080
    depends_on:
      builder:
        condition: service_started
  swaggerui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swaggerui
    environment:
      #- CORS=true
      - SWAGGER_JSON=/appdata/openapi.json
    ports:
      - 8080:8080
    volumes:
      - shared-data:/appdata
    depends_on:
      builder:
        condition: service_completed_successfully
  builder:
    image: python:3-alpine
    container_name: builder
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /src
    volumes:
      - ${PWD}:/src
      - shared-data:/shared-data
    command: >
      /bin/sh -c "pip install -r requirements.txt &&
        python3 ./scripts/build.py -f ./openapi.yaml &&
        mv -f openapi.json /shared-data"
volumes:
  shared-data:
