from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CallbacksPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription_id=None):  # noqa: E501
        """CallbacksPost201Response - a model defined in OpenAPI

        :param subscription_id: The subscription_id of this CallbacksPost201Response.  # noqa: E501
        :type subscription_id: str
        """
        self.openapi_types = {
            'subscription_id': str
        }

        self.attribute_map = {
            'subscription_id': 'subscriptionId'
        }

        self._subscription_id = subscription_id

    @classmethod
    def from_dict(cls, dikt) -> 'CallbacksPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _callbacks_post_201_response of this CallbacksPost201Response.  # noqa: E501
        :rtype: CallbacksPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_id(self) -> str:
        """Gets the subscription_id of this CallbacksPost201Response.

        this unique identifier allows management of the subscription  # noqa: E501

        :return: The subscription_id of this CallbacksPost201Response.
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id: str):
        """Sets the subscription_id of this CallbacksPost201Response.

        this unique identifier allows management of the subscription  # noqa: E501

        :param subscription_id: The subscription_id of this CallbacksPost201Response.
        :type subscription_id: str
        """
        if subscription_id is None:
            raise ValueError("Invalid value for `subscription_id`, must not be `None`")  # noqa: E501

        self._subscription_id = subscription_id
