from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeleteNotificationData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None):  # noqa: E501
        """DeleteNotificationData - a model defined in OpenAPI

        :param timestamp: The timestamp of this DeleteNotificationData.  # noqa: E501
        :type timestamp: datetime
        """
        self.openapi_types = {
            'timestamp': datetime
        }

        self.attribute_map = {
            'timestamp': 'timestamp'
        }

        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteNotificationData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteNotificationData of this DeleteNotificationData.  # noqa: E501
        :rtype: DeleteNotificationData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this DeleteNotificationData.


        :return: The timestamp of this DeleteNotificationData.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this DeleteNotificationData.


        :param timestamp: The timestamp of this DeleteNotificationData.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
