openapi: 3.0.1
info:
  description: Demo spec for documenting openapi functionality
  title: Callback API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://api:8080/v1
- url: https://api.atrakic.dev/v1
paths:
  /callbacks:
    post:
      callbacks:
        onData:
          '{$request.query.callbackUrl}/data':
            delete:
              operationId: on_data_data_delete
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/DeleteNotificationData'
              responses:
                "202":
                  description: |
                    Your server implementation should return this HTTP status code
                    if the data was received successfully
                "204":
                  description: |
                    Your server should return this HTTP status code if no longer interested
                    in further updates
              x-callback-request: true
            post:
              operationId: on_data_data_post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NewNotificationData'
              responses:
                "202":
                  description: |
                    Your server implementation should return this HTTP status code
                    if the data was received successfully
                "204":
                  description: |
                    Your server should return this HTTP status code if no longer interested
                    in further updates
              x-callback-request: true
          '{$request.query.callbackUrl}/test': {}
        dummy: {}
      description: subscribes a client to receive out-of-band data
      operationId: callbacks_post
      parameters:
      - description: |
          the location where data will be sent.  Must be network accessible
          by the source server
        explode: true
        in: query
        name: callbackUrl
        required: true
        schema:
          example: http://server/foo/bar
          format: uri
          type: string
        style: form
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_callbacks_post_201_response'
          description: subscription successfully created
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /healthcheck:
    get:
      description: |
        This endpoint is used to check the health of the API. It should return
        a 200 OK response if the API is up and running.
      operationId: healthcheck_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_healthcheck_get_200_response'
          description: API is up and running
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    NewNotificationData:
      description: subscription payload
      example:
        userData: userData
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        timestamp:
          format: date-time
          title: timestamp
          type: string
        userData:
          title: userData
          type: string
      title: NewNotificationData
    DeleteNotificationData:
      description: subscription payload
      example:
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        timestamp:
          format: date-time
          title: timestamp
          type: string
      title: DeleteNotificationData
    _healthcheck_get_200_response:
      example:
        status: OK
      properties:
        status:
          example: OK
          title: status
          type: string
      title: _healthcheck_get_200_response
      type: object
    _callbacks_post_201_response:
      description: subscription information
      example:
        subscriptionId: 2531329f-fb09-4ef7-887e-84e648214436
      properties:
        subscriptionId:
          description: this unique identifier allows management of the subscription
          example: 2531329f-fb09-4ef7-887e-84e648214436
          title: subscriptionId
          type: string
      required:
      - subscriptionId
      title: _callbacks_post_201_response
