name: docker-compose CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: |
          DOCKER_BUILDKIT=1 docker compose up --quiet-pull --no-color -d
      
      - name: get logs
        run: |
          docker logs postman

      - name: Tear Down Docker Setup
        run: |
          docker compose down
