name: docker-compose CI

on:
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: DOCKER_BUILDKIT=1 docker compose up --quiet-pull --no-color --exit-code-from postman
